name: talat
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.2+2  #Only Update minor version if not major update. in both ios and pubspec.yaml

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_local_notifications:
  firebase_core:
  firebase_messaging: ^14.6.8
  dio: ^5.3.3
  get: ^4.6.6
  connectivity_plus: ^5.0.1
  sms_autofill: ^2.3.0
  fluttertoast: ^8.2.2
  flutter_switch: ^0.3.2
  carousel_slider: ^4.2.1
  pull_to_refresh: ^2.0.0
  google_maps_flutter: ^2.6.1
  google_maps_webservice_ex: ^0.0.1+2
  flutter_map:
  latlng: ^1.0.0
  flutter_date_range_picker: ^0.0.14
  calendar_date_picker2: ^0.5.3
  flutter_rating_bar: ^4.0.1
  shared_preferences:
  flutter_html: ^3.0.0-beta.2
  flutter_spinkit: ^5.2.0
  loading_indicator: ^3.1.1
  url_launcher: ^6.1.14
  flutter_upayments: ^1.0.2
  map_launcher: ^3.0.1
  dropdown_button2: ^2.3.9
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  flutter_svg:
  permission_handler: ^11.0.0
  overlay_support: ^2.1.0
  google_api_headers: ^2.0.2
  firebase_analytics:
  google_fonts:
  shimmer:
  intl:
  firebase_crashlytics: ^3.5.5
  flutter_widget_from_html:
  syncfusion_flutter_datepicker: ^23.1.38
  device_info_plus: ^9.0.3
  video_player: ^2.8.1

dependency_overrides:
  flutter_inappwebview: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/map_icons/
    - assets/videos/talat_splash_clip.mp4

  fonts:
    - family: Helvetica-Neue-Font
      fonts:
        - asset: assets/fonts/Helvetica-Neue-Font/Helvetica Neue LTW0697BlkCnObl.ttf
        - asset: assets/fonts/Helvetica-Neue-Font/Helvetica Neue Medium Extended.ttf
        - asset: assets/fonts/Helvetica-Neue-Font/Helvetica Neue UltraLight.ttf
        - asset: assets/fonts/Helvetica-Neue-Font/Helvetica Neue W01 66 Medium It.ttf
        - asset: assets/fonts/Helvetica-Neue-Font/Helvetica Neue W01 77 Bd Cn Obl.ttf
        - asset: assets/fonts/Helvetica-Neue-Font/Helvetica Neue W01 87 Hv Cn Obl.ttf
        - asset: assets/fonts/Helvetica-Neue-Font/Helvetica NeueLTW0693BlkExtObl.ttf